### ISSUE TITLE
Request: manually choose decks in an existing result

### ISSUE THREAD

**Issue by jakeboxer** [stevschmid/trackobot.com#13]
First of all, thank you so much for Track-o-bot! I'm on a Mac, and this is the first Hearthstone tracking app I've used that's been stable and felt good.

Anyways, my request: I just had a game that went like this:

![](http://cl.ly/image/0s2l0u3O1q2J/Image%202015-02-17%20at%2010.40.56%20PM.png)

Turn 3 Ragnaros rules, but the game was over so quick, Track-o-bot wasn't able to identify my deck :( I'd love it if there were a way to choose which deck I used so that I don't have to add key cards to my deck that don't really identify it (Wild Growth, Innervate, and Ragnaros are probably run in every Druid deck, and The Black Knight doesn't really distinguish between any of them either).

I write Rails full-time, so if you could suggest a strategy for implementing this, I'd be happy to give it a shot when I have some spare time!

**Comment by stevschmid** [comment]
Turn 2 Wild Growth into double Innervate Ragnaros into coin Black Knight to kill of his Sen'jin. **Wow!**

I see the main challenge of manually choosing/setting a deck in the UI. An anobtrusive edit button (e.g. only shown when hovering over the specific match) + inline edit form (with autocomplete boxes for both the player and opponent to choose class or deck) could do the trick.

**Comment by gssjr** [comment]
@jakeboxer Perhaps we should coordinate since I'm also implementing an edit result functionality (in this case deletion. See #12 ). Don't want to step on your toes UI/UX-wise if we're developing this simultaneously.

I was trying to emulate the feel of gmail/inbox when selecting results to perform bulk-actions. The challenge here would be that we can edit either player or opponent deck names. Perhaps switching my checkbox to an Edit type button which allow multiple functions: delete record, edit deck name, etc... Although, it'd be nice to keep the bulk-edit/delete functionality. Any ideas?

**Comment by satyrius** [comment]
Hi @jakeboxer! +1 for the feature request. @stevschmid, my situation was even more unpredictable for automatic deck matching: on turn 2 Priest played Deathlord, then it was suddenly executed by me and Dr. Boom was dropped on the table. He conceded. No chance to match both deck types.

<img width="485" alt="screenshot 2015-08-17 03 37 54" src="https://cloud.githubusercontent.com/assets/278630/9296286/f0a09062-4491-11e5-903b-5507666959ce.png">

**Comment by stevschmid** [comment]
@satyrius @jakeboxer The ability to override the deck recognition arrives soon™ :smiley:

**Comment by stevschmid** [comment]
Should be up soon.
